# Generated by Django 3.1 on 2020-08-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
