# Generated by Django 3.1 on 2020-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='', verbose_name='Изображения', width_field='picture_width'),
        ),
    ]
