# Generated by Django 3.1 on 2020-08-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_resulttable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultTable',
        ),
    ]
