# Generated by Django 3.1 on 2020-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_resulttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=255, unique=False, verbose_name='Адрес электронной почты'),
        ),
    ]
