# Generated by Django 3.1 on 2020-08-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_resulttable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulttable',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Адрес электронной почты'),
        ),
    ]
