# Generated by Django 3.1 on 2020-08-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200814_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
