# Generated by Django 3.1 on 2020-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200814_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
    ]
