# Generated by Django 3.1 on 2020-08-15 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20200815_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(default='none', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_at',
            field=models.CharField(blank=True, choices=[('GA-36', 'ГА-36'), ('GAC', 'ГАЦ'), ('CSU', 'ЦСЮ')], max_length=50, verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='middle_name',
            field=models.CharField(default='none', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='resulttable',
            name='passing_test_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата прохождения теста'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
