# Generated by Django 3.1 on 2020-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20200815_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='working_at',
            field=models.CharField(choices=[('GA-36', 'ГА-36'), ('GAC', 'ГАЦ'), ('CSU', 'ЦСЮ')], default=424, max_length=50, verbose_name='Место работы'),
            preserve_default=False,
        ),
    ]
