# Generated by Django 3.1 on 2020-08-20 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_resulttable_working_at'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='questions',
    #        name='id',
    #    ),
    #    migrations.AddField(
    #        model_name='questions',
    #        name='question_id',
   #         field=models.AutoField(default=uuid.UUID('a82ba728-2b85-4875-b34d-cff1f39bb0ae'), primary_key=True, serialize=False),
   ##         preserve_default=False,
    #   ),
    #]
