# Generated by Django 3.1 on 2020-08-20 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20200820_2246'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='questions',
    #        name='question_id',
    #        field=models.AutoField(default=uuid.UUID('a82ba728-2b85-4875-b34d-cff1f39bb0ae'), primary_key=True, serialize=False),
    #    ),
    #]
