# Generated by Django 3.1 on 2020-08-20 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20200820_2257'),
    ]

   # operations = [
   #     migrations.AlterField(
   #         model_name='questions',
   #         name='question_id',
   #         field=models.AutoField(default=uuid.UUID('ef2dd63b-a208-4293-bde5-131d5cb1e21d'), primary_key=True, serialize=False),
   #     ),
   # ]
