# Generated by Django 3.1 on 2020-08-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20200820_2259'),
    ]

   # operations = [
   #     migrations.RemoveField(
    #        model_name='questions',
    #        name='question_id',
    #    ),
    #    migrations.AddField(
    #        model_name='questions',
    #        name='id',
    #        field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
   #         preserve_default=False,
   #     ),
    #]
