# Generated by Django 3.1 on 2020-08-20 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20200820_2301'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='questions',
    #        name='id',
    #   ),
    #    migrations.AddField(
    #        model_name='questions',
    #        name='question_id',
    ##        field=models.AutoField(default=uuid.UUID('c84270d5-4c6f-40b9-8867-f6e941495f3b'), primary_key=True, serialize=False),
    #    ),
    #]
