# Generated by Django 3.1 on 2020-08-20 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20200820_2302'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='questions',
     #       name='question_id',
     #       field=models.AutoField(default=uuid.UUID('2f05a9f5-b4b0-498a-b242-d800fadda988'), primary_key=True, serialize=False),
     #   ),
    #]
