# Generated by Django 3.1 on 2020-08-20 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20200820_2304'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='questions',
    #        name='question_id',
    #        field=models.AutoField(default=uuid.UUID('90d032bc-10a5-4e07-8fc6-b698616d7dab'), primary_key=True, serialize=False),
    #    ),
    #]
