# Generated by Django 3.1 on 2020-08-20 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_auto_20200820_2312'),
    ]

    #operations = [
    #    migrations.RemoveField(
    #        model_name='questions',
     #       name='question_id',
     #   ),
     #   migrations.AddField(
      #      model_name='questions',
      #      name='id',
      #      field=models.AutoField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
      #      preserve_default=False,
      #  ),
    #]
