# Generated by Django 3.1 on 2020-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_auto_20200821_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='right_ans_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент правильных ответов'),
        ),
    ]
