# Generated by Django 3.1 on 2020-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_resulttable_right_ans_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.BooleanField(default=False, verbose_name='Первый разряд'),
        ),
    ]
