# Generated by Django 3.1 on 2020-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_customuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttable',
            name='wrong_answers',
            field=models.TextField(blank=True, null=True, verbose_name='Неправильные ответы'),
        ),
    ]
